@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

actor User

box UI UI_COLOR_T1
participant ":CommandBox" as CommandBox UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":StarCommandParser" as StarCommandParser LOGIC_COLOR
participant "s:StarCommand" as StarCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "personToStar:Person" as personToStar MODEL_COLOR
participant "starredPerson:Person" as starredPerson MODEL_COLOR
end box

box #6CA6CD
participant "lastShownList:List<Person>" as lastShownList #6CA6CD
endbox

User -> CommandBox : enterCommand("star 1")
activate CommandBox

CommandBox -> LogicManager : execute("star 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("star 1")
activate AddressBookParser

create StarCommandParser
AddressBookParser -> StarCommandParser
activate StarCommandParser

StarCommandParser --> AddressBookParser
deactivate StarCommandParser

AddressBookParser -> StarCommandParser : parse("1")
activate StarCommandParser

create StarCommand
StarCommandParser -> StarCommand
activate StarCommand

StarCommand --> StarCommandParser
deactivate StarCommand

StarCommandParser --> AddressBookParser : s
deactivate StarCommandParser
' Hidden arrow to position destroy marker below activation bar
StarCommandParser -[hidden]-> AddressBookParser
destroy StarCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> StarCommand : execute(m)
activate StarCommand

StarCommand -> Model : getFilteredPersonList()
activate Model
Model --> StarCommand : lastShownList
deactivate Model

StarCommand -> lastShownList : get(index=0)
activate lastShownList
lastShownList --> StarCommand : personToStar
deactivate lastShownList

StarCommand -> personToStar : isStarred()
activate personToStar
personToStar --> StarCommand : false
deactivate personToStar

StarCommand -> personToStar : rebuildWithStarredStatus(true)
activate personToStar

create starredPerson
personToStar -> starredPerson
activate starredPerson

starredPerson --> personToStar
deactivate starredPerson

personToStar --> StarCommand : starredPerson
deactivate personToStar

StarCommand -> Model : setPerson(personToStar, starredPerson)
activate Model
Model --> StarCommand
deactivate Model

StarCommand -> Model : sortPersons(STARRED_STATUS_COMPARATOR)
activate Model
Model --> StarCommand
deactivate Model

StarCommand -> Model : setToActiveList()
activate Model
Model --> StarCommand
deactivate Model

StarCommand -> Model : refreshFilteredPersonList()
activate Model
Model --> StarCommand
deactivate Model

create CommandResult
StarCommand -> CommandResult
activate CommandResult

CommandResult --> StarCommand : r
deactivate CommandResult

StarCommand --> LogicManager : r
deactivate StarCommand

'Hidden arrow to position the destroy marker below the end of the activation bar.
StarCommand -[hidden]-> LogicManager
destroy StarCommand

LogicManager --> CommandBox : CommandResult
deactivate LogicManager

'Hidden arrow to position the destroy marker below the end of the activation bar.
personToStar -[hidden]-> LogicManager
destroy personToStar

CommandBox --> User : display success message
deactivate CommandBox

@enduml
